version: '3'

services:
    samba:
      build: ./img/samba/.
      container_name: ${PRJ_BASE_NAME}_server
      tty: true
      ports:
        - "139:139"
        - "445:445"
      env_file:
        - .env
      volumes:
        - ./vol/samba/publico:/mnt
        - ./vol/samba/privado:/mnt2
        - ./vol/samba/usr1:/mnt3
        - ./vol/samba/usr2:/mnt4
        - ./conf/samba:/etc/samba